### ISSUE TITLE
backend: fixa så att mariadb initialiseras med sql

### ISSUE THREAD

**Issue by sonnerberg** [virtuella-team/vteam#6]
Docker-containern bör startas med sql-kod likt hur vi använde mappen sql.d i databas-kursen.

[vteam/docker-compose.yml at tzLocal · virtuella-team/vteam](https://github.com/virtuella-team/vteam/blob/tzLocal/docker-compose.yml)

[vteam/mariadb/sql at tzLocal · virtuella-team/vteam](https://github.com/virtuella-team/vteam/tree/tzLocal/mariadb/sql)

**Comment by tomas-zw** [comment]
Nu finns mariadb/init_data för att lägga in .csv filer. Läs  in dom från mariadb/init.sql

**Comment by sonnerberg** [comment]
Snyggt. Uppdaterar du docker-compose också?

**Comment by tomas-zw** [comment]
Japp, har ändrat den
