### ISSUE TITLE
backend: github actions

### ISSUE THREAD

**Issue by sonnerberg** [virtuella-team/vteam#7]

**Comment by tomas-zw** [comment]
Finns nu fungerande workflow, i " backend" branch, med olika tester och codecoverage. Stänger inte denna före ni kikat på den så det inte är tokigt nånstans.

**Comment by tomas-zw** [comment]
Det visar sig att Docker compose funkar alldeles utmärkt med `runs-on: ubuntu:latest` i en workflow. Så jag har ändrat workflow att bygga upp containrarna i testmiljön med våra färdiga compose filer som grund. Tex i "backend" branchens CI byggs bara mariadb och express upp (docker-compose-CI.yml). Jag tror att detta kan vara en smidig lösning för att enkelt fixa olika workflows för olika tester.
